name: dartNotionAPI
description: a wrapper around notion API in dart.
version: 1.0.0
homepage: https://github.com/nabildroid/dart-notionAPI

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http:

dev_dependencies:
  pedantic: ^1.9.0
  meta:
