name: dartNotionAPI
description: a wrapper around notion API in dart.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'
  http:
#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
